#! /bin/bash

# Buscador avanzado

# Busca archivos regulares en todo el sistema cuyo nombre coincida con un patrón proporcionado
# Busca archivos regulares en todo el sistema cuyo nombres tengan una longitud igual a un valor entero y positivo dado.

# Genera un listado de una sola columna con el direccionamiento absoluto del archivo.
# SIN SALIDA DE ERRORES
# Llamada en vacío, con menos parámetros de los obligatorios o param incorrectos, sale un texto explicativo.

# -c
## argumento_de_busqueda es un número entero mayor a cero y busca archivos regulares cuyo nombre sea de la longitud de argumento_de_busqueda

# -p
## argumento_de_busqueda es una cadena de caracteres

function ERROR() {
cat << EOF
SINOPSIS
	$0 -c|-p argumento_de_busqueda

OPCIONES
	-c
		argumento_de_busqueda será un número entero mayor a cero. Buscará ficheros regulares cuyo nombre tengan una longitud de caracteres igual al número introducido.

	-p
		argumento_de_busqueda será una cadena de caracteres. Buscará ficheros regulares cuyo nombre coincida con el patrón proporcionado.
EOF
}

if (( ${#@} != 2 )); then
	echo "Debes introducir dos parámetros.";
	ERROR;
fi

if [[ $1 != "-c" && $1 != "-p" ]]; then
	echo "El primer parámetro debe ser una de las opciones -c o -p.";
	ERROR;
fi

if [[ $1 == "-c" ]]; then
	if [[ $2 =~ ^[[:digit:]]+$ && $2 -gt 0 ]]; then
		find / -type f 2>/dev/null | while read -r fich; do
			name=$(basename $fich);
			if (( ${#name} == $2 )); then
				echo $fich;
			fi
		done
	else
		echo "El segundo parámetro debe ser un número entero mayor a 0.";
		ERROR;
	fi
fi


# El enunciado dice "ficheros cuyo nombre coincida con un patrón proporcionado".
# Es un poco ambiguo y no sé si se refiere a que el nombre completo debe coincidir o si el patrón debe estar
# contenido en el nombre del fichero. En mi ejercicio, sólo devolverá los ficheros cuyo nombre completo coincidan
# con el patrón dado.

if [[ $1 == "-p" ]]; then
	if [[ $2 =~ ^[[:alnum:]]+$ ]]; then
		find / -type f -name "$2" 2>/dev/null;
	else
		echo "El patrón debe contener únicamente caracteres alfanuméricos.";
		ERROR;
	fi
fi
