#! /bin/bash

# 1. Recoger el numero de parametros con $#
# 2. Con for, ejecutar chmod o+x para los ficheros pasados como parametros
# 3. Si el usuario no es el mismo que el propietario, no se ejecuta el chmod

parms=("$@");

for i in "${parms[@]}"; do
	owner=$(ls -l $i | cut -f3 -d" ");
	if [[ "$owner" == "$USER" ]]; then
		chmod o+x $i;
	else
		echo "No eres propietario del fichero $i";
	fi
done
